export interface GalleryItem {
  id: string;
  code: string;
  title: string;
  category: "training" | "vip" | "event" | "facility" | "command" | "video";
  categoryLabel: string;
  src: string;
  isVideo?: boolean;
  aspect?: "square" | "landscape" | "portrait" | "wide";
  bentoSpan: {
    cols: string; // Tailwind col classes
    rows: string; // Tailwind row classes
  };
  location: string;
  unit: string;
  clearance: string;
  description: string;
}

export const galleryCategories = [
  { id: "all", label: "ALL OPERATIONS", icon: "Layers" },
  { id: "training", label: "TRAINING & FORMATIONS", icon: "Award" },
  { id: "vip", label: "VIP & CLOSE PROTECTION", icon: "UserCheck" },
  { id: "event", label: "EVENT & STADIUM SECURITY", icon: "Flame" },
  { id: "facility", label: "FACILITY & INDUSTRIAL", icon: "Building2" },
  { id: "command", label: "CORPORATE & SOC COMMAND", icon: "Monitor" },
  { id: "video", label: "OPERATIONAL VIDEO", icon: "PlaySquare" },
] as const;

export const galleryItems: GalleryItem[] = [
  // ─── FEATURED VIDEO ──────────────────────────────────────────
  {
    id: "media-video-01",
    code: "VID-OPS-01",
    title: "Stronghold Tactical Deployment Reel",
    category: "video",
    categoryLabel: "Operational Video",
    src: "/drive-images/0830.mp4",
    isVideo: true,
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "National Operations Command",
    unit: "Field Deployment Wing",
    clearance: "LEVEL 4 COMMAND",
    description: "Live operational footage demonstrating tactical guard force discipline, perimeter deployment, and specialized field presence.",
  },

  // ─── TRAINING & DRILLS ─────────────────────────────────────────
  {
    id: "img-tr-01",
    code: "OP-TR-01",
    title: "Battalion Muster & Parade Formation",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_31 PM (16).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "Stronghold Academy Drill Grounds",
    unit: "Central Training Brigade",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Full guard force array undergoing precision tactical muster, formal drill inspection, and readiness verification.",
  },
  {
    id: "img-tr-02",
    code: "OP-TR-02",
    title: "Academy Cadet Corps Formation",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_28 PM (15).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Academy Training Facility",
    unit: "Polo Corps Trainees",
    clearance: "LEVEL 2 TACTICAL",
    description: "New recruit cadre undergoing military drill instruction, protocol conditioning, and tactical readiness tests.",
  },
  {
    id: "img-tr-03",
    code: "OP-TR-03",
    title: "Guard Force Pre-Shift Alignment",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_26 PM (14).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Regional Station Terminal",
    unit: "Officer Patrol Division",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Female and male security officers standing at attention during pre-deployment posture and communications inspection.",
  },
  {
    id: "img-tr-04",
    code: "OP-TR-04",
    title: "Strategic Operations Briefing",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_51 PM (4).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Headquarters Briefing Room",
    unit: "Command & Control Staff",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Operational leadership briefing commanders on high-threat sector protocols and emergency incident response.",
  },
  {
    id: "img-tr-06",
    code: "OP-TR-06",
    title: "Station Field Muster Drill",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_49 PM (1).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Industrial Sector Terminal",
    unit: "Field Deployment Cadre",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Guard squad aligned in military formation for daily roll-call and site assignment distribution.",
  },
  {
    id: "img-tr-05",
    code: "OP-TR-05",
    title: "Rooftop Tactical Skyline Inspection",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_40 PM (2).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Metropolitan High-Rise Deck",
    unit: "Tactical Response Unit",
    clearance: "LEVEL 2 TACTICAL",
    description: "Precision squad muster overlooking the urban skyline under sunrise readiness protocols.",
  },
  {
    id: "img-tr-07",
    code: "OP-TR-07",
    title: "Tactical Discipline & Posture Review",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_50 PM (2).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Training Depot West",
    unit: "Inspection Division",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Evaluating uniform standards, radio equipment integrity, and physical demeanor before field deployment.",
  },
  {
    id: "img-tr-08",
    code: "OP-TR-08",
    title: "Advanced Tactical Formation Review",
    category: "training",
    categoryLabel: "Training & Formations",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_50 PM (3).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Training Depot North",
    unit: "Field Cadre",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Rigorous field discipline conditioning emphasizing posture, attentiveness, and military command execution.",
  },

  // ─── VIP & CLOSE PROTECTION ─────────────────────────────────────
  {
    id: "img-vip-01",
    code: "OP-VIP-01",
    title: "Elite Tier-1 Close Protection Unit",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_03 PM (1).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "Diplomatic Sector Enclave",
    unit: "Executive Protection Wing",
    clearance: "LEVEL 4 TOP SECRET",
    description: "Four-officer close protection detail prepared for high-profile dignitary transit and rapid evacuation protocols.",
  },
  {
    id: "img-vip-02",
    code: "OP-VIP-02",
    title: "Tactical Field Comms Coordinator",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_05 PM (2).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Transit Corridor Alpha",
    unit: "Tactical Escort Detail",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Lead operative coordinating encrypted tactical frequencies for real-time motorcade route clearance.",
  },
  {
    id: "img-vip-03",
    code: "OP-VIP-03",
    title: "Executive Bodyguard & Shadow Escort",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_07 PM (3).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "VIP Compound Perimeter",
    unit: "Close Protection Detail",
    clearance: "LEVEL 4 TOP SECRET",
    description: "Specialist bodyguard maintaining 360-degree situational awareness and close physical barrier positioning.",
  },
  {
    id: "img-vip-04",
    code: "OP-VIP-04",
    title: "Tactical Lead Briefing & Escort Comms",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_15 PM (8).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Commercial District Corridor",
    unit: "Executive Guard Unit",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Close protection team maintaining radio contact and executing high-level observation maneuvers.",
  },
  {
    id: "img-vip-05",
    code: "OP-VIP-05",
    title: "Perimeter Threat Reconnaissance Team",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_13 PM (7).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Outer Security Zone",
    unit: "Advance Recon Unit",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Two-man advance team identifying potential chokepoints and vector threats along executive movement lines.",
  },
  {
    id: "img-vip-07",
    code: "OP-VIP-07",
    title: "Tactical Communications Officer",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_42 PM (7).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Financial Center Perimeter",
    unit: "Command Comms Lead",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Operative broadcasting perimeter telemetry and managing encrypted multichannel radio links.",
  },
  {
    id: "img-vip-06",
    code: "OP-VIP-06",
    title: "Rapid Escort Lead Operative",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_09 PM (4).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "City Transit Hub",
    unit: "VIP Escort Lead",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Lead field operative maintaining strict perimeter surveillance and instant defensive posture.",
  },
  {
    id: "img-vip-08",
    code: "OP-VIP-08",
    title: "High-Profile Close Protection Array",
    category: "vip",
    categoryLabel: "VIP & Close Protection",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_42 PM (8).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Diplomatic Complex",
    unit: "VIP Array Detail",
    clearance: "LEVEL 4 TOP SECRET",
    description: "Full bodyguard formation configured for immediate physical shielding and sterile-zone enforcement.",
  },

  // ─── EVENT & STADIUM SECURITY ──────────────────────────────────
  {
    id: "img-ev-01",
    code: "OP-EV-01",
    title: "International Stadium Security Squad",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_21 PM (11).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "National Stadium Complex",
    unit: "Stadium Division Delta",
    clearance: "LEVEL 2 TACTICAL",
    description: "Multidisciplinary security squad deployed for international match fixture, crowd control, and VIP player tunnel safety.",
  },
  {
    id: "img-ev-02",
    code: "OP-EV-02",
    title: "Arena Crowd Access & Marshalling Detail",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_10 PM (5).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Grandstand Pavilion Gates",
    unit: "Female Officer Division",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Female security officers overseeing stadium access gates, spectator flow management, and emergency exit routes.",
  },
  {
    id: "img-ev-03",
    code: "OP-EV-03",
    title: "Stadium VIP Sector Tactical Guard Force",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_12 PM (6).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Main Arena Stand",
    unit: "VIP Event Protection",
    clearance: "LEVEL 2 TACTICAL",
    description: "Tattooed tactical specialists and ear-piece operators guarding the royal box and official delegates area.",
  },
  {
    id: "img-ev-04",
    code: "OP-EV-04",
    title: "Pitch-Side Incident Response Operatives",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_19 PM (10).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Arena Field Boundary",
    unit: "Rapid Incident Response",
    clearance: "LEVEL 2 TACTICAL",
    description: "Trained pitch-side security operatives positioned to prevent field pitch invasion and ensure attendee welfare.",
  },
  {
    id: "img-ev-06",
    code: "OP-EV-06",
    title: "Public Event Coordination Squad",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_40 PM (4).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Exhibition Convention Center",
    unit: "Crowd Marshal Wing",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Specialized team monitoring crowd density, queuing queues, and ticketing verification checkpoints.",
  },
  {
    id: "img-ev-05",
    code: "OP-EV-05",
    title: "Sports Arena Security Array",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_22 PM (12).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Sports Stadium Perimeter",
    unit: "Crowd Security Detachment",
    clearance: "LEVEL 2 TACTICAL",
    description: "Tactical deployment of personnel maintaining rigorous security perimeter during massive public events.",
  },
  {
    id: "img-ev-07",
    code: "OP-EV-07",
    title: "Access Point Security Coordination",
    category: "event",
    categoryLabel: "Event & Stadium Security",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_41 PM (5).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Festival Grounds West",
    unit: "Event Security Detachment",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Rigorous entry scanning, metal detection checkpoints, and bag inspections for large-scale gathering security.",
  },

  // ─── FACILITY & INDUSTRIAL GUARDING ────────────────────────────
  {
    id: "img-fc-01",
    code: "OP-FC-01",
    title: "Mihila Tex Industrial Logistics Guard Force",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_25 PM (13).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "Mihila Tex by Hirdaramani",
    unit: "Industrial Guard Division",
    clearance: "LEVEL 2 TACTICAL",
    description: "Guard squad deployed at major export garment manufacturing facility, securing freight loading bays and employee access.",
  },
  {
    id: "img-fc-02",
    code: "OP-FC-02",
    title: "Kandetiya Agro Products Main Gate Access",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_51 PM (6).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Kandetiya Agro Products Facility",
    unit: "Access Gate Division",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Dedicated access control and vehicle dispatch team protecting agricultural production plants and cargo yards.",
  },
  {
    id: "img-fc-03",
    code: "OP-FC-03",
    title: "Industrial Complex Perimeter Squad",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_08_51 PM (5).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Industrial Export Processing Zone",
    unit: "Perimeter Patrol Force",
    clearance: "LEVEL 2 TACTICAL",
    description: "Five-member security team responsible for 24/7 patrol rounds, boundary sensors, and fence integrity checks.",
  },
  {
    id: "img-fc-04",
    code: "OP-FC-04",
    title: "Static Commercial Facility Patrol Officers",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 05_00_17 PM (9).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Commercial Park North",
    unit: "Static Guard Detachment",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Officers conducting regular ground rounds, visitor validation, and emergency exit monitoring.",
  },
  {
    id: "img-fc-05",
    code: "OP-FC-05",
    title: "Warehouse & Supply Chain Guard Unit",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_41 PM (6).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Central Logistics Hub",
    unit: "Supply Chain Protection",
    clearance: "LEVEL 2 TACTICAL",
    description: "Logistics asset protection squad preventing cargo loss, pilferage, and unauthorized vehicle entry.",
  },
  {
    id: "img-fc-06",
    code: "OP-FC-06",
    title: "Industrial Gate Surveillance Detail",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_43 PM (9).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Heavy Manufacturing Enclave",
    unit: "Gate Control Unit",
    clearance: "LEVEL 1 UNRESTRICTED",
    description: "Automated biometric logging and physical guard verification at primary heavy freight checkpoints.",
  },
  {
    id: "img-fc-07",
    code: "OP-FC-07",
    title: "Commercial Asset Defense Squad",
    category: "facility",
    categoryLabel: "Facility & Industrial",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_43 PM (10).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Corporate Warehouse East",
    unit: "Asset Defense Unit",
    clearance: "LEVEL 2 TACTICAL",
    description: "On-site security officers providing round-the-clock physical surveillance and anti-intrusion deterrence.",
  },

  // ─── CORPORATE & COMMAND OPERATIONS ────────────────────────────
  {
    id: "img-cmd-01",
    code: "OP-CMD-01",
    title: "SOC Glass Command Center Surveillance Squad",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_40 PM (3).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2 lg:col-span-2",
      rows: "row-span-1 md:row-span-2",
    },
    location: "Stronghold Central SOC Facility",
    unit: "SOC Surveillance Wing",
    clearance: "LEVEL 4 TOP SECRET",
    description: "Security Operations Center squad standing guard before active 24/7 CCTV surveillance video walls and digital sensors.",
  },
  {
    id: "img-cmd-02",
    code: "OP-CMD-02",
    title: "Metropolitan Corporate Security Taskforce",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_24_25 PM (1).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Colombo World Trade District",
    unit: "Corporate Rapid Reaction",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Evening high-readiness taskforce protecting premium high-rise corporate towers and executive boardrooms.",
  },
  {
    id: "img-cmd-03",
    code: "OP-CMD-03",
    title: "Corporate Plaza Overwatch & Protection",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_34_39 PM (1).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Modern Glass Corporate Plaza",
    unit: "Headquarters Security Squad",
    clearance: "LEVEL 2 TACTICAL",
    description: "Guard force array deployed at the marble glass concourse of an enterprise multinational headquarters.",
  },
  {
    id: "img-cmd-04",
    code: "OP-CMD-04",
    title: "High-Rise Headquarters Static Detail",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_24_26 PM (2).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Financial Center Tower",
    unit: "Building Access Division",
    clearance: "LEVEL 2 TACTICAL",
    description: "Front-line security officers safeguarding high-traffic executive lobbies and keycard turnstile zones.",
  },
  {
    id: "img-cmd-05",
    code: "OP-CMD-05",
    title: "Corporate Plaza Night Surveillance",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_24_26 PM (3).png",
    aspect: "landscape",
    bentoSpan: {
      cols: "col-span-1 md:col-span-1",
      rows: "row-span-1",
    },
    location: "Skyline Financial Plaza",
    unit: "Night Patrol Unit",
    clearance: "LEVEL 2 TACTICAL",
    description: "Night surveillance guard squad equipped with tactical flashlights, bodycams, and panic alarm linkups.",
  },
  {
    id: "img-cmd-06",
    code: "OP-CMD-06",
    title: "Central Business District Response Unit",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_24_26 PM (4).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Metropolitan Financial Core",
    unit: "Rapid Deployment Unit",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Mobile tactical unit ready for emergency alarm dispatch and immediate on-site perimeter lockdown.",
  },
  {
    id: "img-cmd-07",
    code: "OP-CMD-07",
    title: "Executive Boardroom Security Guard Force",
    category: "command",
    categoryLabel: "Corporate & SOC Command",
    src: "/drive-images/ChatGPT Image Aug 30, 2026, 06_24_27 PM (5).png",
    aspect: "wide",
    bentoSpan: {
      cols: "col-span-1 md:col-span-2",
      rows: "row-span-1",
    },
    location: "Enterprise Tower Level 28",
    unit: "Executive Concierge Security",
    clearance: "LEVEL 3 CONFIDENTIAL",
    description: "Discreet and sharp corporate officers managing executive suite confidentiality, visitor escorts, and access rights.",
  },
];
